archive_dir: archives
author: Xinyu Han
category_dir: categories
category_map: null
code_dir: downloads/code
date_format: YYYY-MM-DD
default_category: uncategorized
default_layout: post
deploy:
  branch: main
  repo: https://github.com/XinyuKhan/xinyukhan.github.io.git
  type: git
description: ''
exclude: null
external_link:
  enable: true
  exclude: ''
  field: site
filename_case: 0
future: true
highlight:
  auto_detect: false
  hljs: false
  line_number: true
  tab_replace: ''
  wrap: true
i18n_dir: :lang
ignore: null
include: null
index_generator:
  order_by: -date
  path: ''
  per_page: 10
keywords: null
language: zh-CN


mathjax:
  tags: none
  single_dollars: true
  cjk_width: 0.9
  normal_width: 0.6
  append_css: true
  every_page: true

# Settings recovered safely
title: "Xinyu's Blog"
url: http://example.com
permalink: :year/:month/:day/:title/
theme: fluid

markdown:
  render:
    html: true
    breaks: true
    linkify: true
    typographer: true
  plugins:
    - markdown-it-katex
